services:
  web:
    build: .
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://evoting:password@db/evoting
      - SECRET_KEY=your-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=evoting
      - POSTGRES_USER=evoting
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
