services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"        # HTTPS port
      - "80:80"          # Redirect to HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - web
    restart: always

  web:
    build: .
    container_name: flask_backend
    expose:
      - "5000"           # expose only internally no direct access
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://evoting:password@db/evoting
      - SECRET_KEY=your-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - opa
    volumes:
      - .:/app
      - ./logs:/app/logs
    restart: always

  opa:
    image: openpolicyagent/opa:0.60.0
    container_name: opa
    command: run --server --set=decision_logs.console=true /opa-policies/rbac.rego
    ports:
      - "8181:8181"
    volumes:
      - ./opa-policies/rbac.rego:/opa-policies/rbac.rego
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    restart: always

  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=evoting
      - POSTGRES_USER=evoting
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: