services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://evoting:password@db/evoting
      - SECRET_KEY=your-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - opa
    volumes:
      - .:/app
      - ./logs:/app/logs

  opa:
    image: openpolicyagent/opa:0.60.0
    command: run --server --set=decision_logs.console=true /opa-policies/rbac.rego
    ports:
      - "8181:8181"
    volumes:
      - ./opa-policies/rbac.rego:/opa-policies/rbac.rego

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=evoting
      - POSTGRES_USER=evoting
      - POSTGRES_PASSWORD=password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
